fixing the care and support update form
lamisplus/HIV-Module pull request #31
Opened 2023-11-10 11:49 UTC by Mathew77

fixing the care and support update form

2023-11-10 12:01 UTC, lilkersy commented on src/main/java/org/lamisplus/modules/hiv/repositories/HivEnrollmentRepository.java
Was the group by statement in the previous query giving an issue? I see that the whole query was changed to reflect the correct parameters for the "ilike"?

2023-11-10 12:06 UTC, lilkersy commented on src/main/java/org/lamisplus/modules/hiv/service/HivPatientService.java
What is the difference between if (!((searchValue == null) || (searchValue.equals("*")))) and if ((searchValue != null) || (!searchValue.equals("*"))). If the former seems to work. I would be curious to know why though.

2023-11-10 12:09 UTC, lilkersy commented on src/main/webapp/jsx/components/ChronicCare/Tb.js
These two fields           
1. ["status"]: "Currently on TB Treatment", (old) and 
2. ["status"]: "Currently on TB treatment", (new). If this appears on the UI then it I presume it would appear on the RADET as well. Considering how data are counted on the RADET, inconsistent namings might cause an issue. Can we standardize these namings (eg. using Ii8n)?

2023-11-10 12:10 UTC, lilkersy commented on src/main/webapp/jsx/components/Consultation/Home.js
This is a really cool spotting and implementation. However, is there also a consideration for weight, somewhere in the code when valuating for children above say 30kg?

2023-11-10 12:21 UTC, lilkersy commented on src/main/webapp/jsx/components/History/RecentHistory.js
const [vitaLoad, setViralLoad] = useState([]); Is this mean to be viralLoad instead of VitaLoad?

2023-11-10 12:25 UTC, lilkersy commented on src/main/webapp/jsx/components/Otz/ServiceForm.js
Does setting this facilityId: null, (line 97) have any effect?

2023-11-10 12:32 UTC, lilkersy commented on src/main/webapp/jsx/components/TrackingForm/Tracking.js
What is the difference between this "setSaving" and the "setSavings" in the OtzServiceForm.js? Is it just a nomenclature definition thing?

2023-11-10 12:35 UTC, lilkersy requested changes
I have taken look at the code and asked a couple of questions. Please review.

2023-11-12 01:51 UTC, Mathew77 commented on src/main/java/org/lamisplus/modules/hiv/repositories/HivEnrollmentRepository.java
It's not but @dikumheartland  said for othername that are migrated and empty are not pulling. 
@dikumheartland can you please provide more clearity.

2023-11-12 01:52 UTC, Mathew77 commented on src/main/java/org/lamisplus/modules/hiv/service/HivPatientService.java
It's not but @dikumheartland said for othername that are migrated and empty are not pulling.
@dikumheartland can you please provide more clarity.

2023-11-12 01:54 UTC, Mathew77 commented on src/main/webapp/jsx/components/ChronicCare/Tb.js
Yes it will appear, because it is just the display name that was change which RADET is using the application_codeset code to get the value.

2023-11-12 01:58 UTC, Mathew77 commented on src/main/webapp/jsx/components/Consultation/Home.js
Please can you provide more context to this. Because I can't see that in the home.js

2023-11-12 01:59 UTC, Mathew77 commented on src/main/webapp/jsx/components/History/RecentHistory.js
Yes, it should be ViralLoad.

2023-11-12 02:03 UTC, Mathew77 commented on src/main/webapp/jsx/components/History/RecentHistory.js
Fixed

2023-11-12 02:10 UTC, Mathew77 commented
@lilkersy thank you so much for your review, corrections made where necessary.

2023-11-12 13:37 UTC, lilkersy commented on src/main/webapp/jsx/components/Consultation/Home.js
Yea, I think there were previous implementations especially in the LAMIS3 where weight is also considered for peads, or are we letting go of that condition?

2023-11-12 13:39 UTC, lilkersy commented on src/main/webapp/jsx/components/ChronicCare/Tb.js
Alright, I think I understand.

2023-11-12 14:25 UTC, Mathew77 commented on src/main/webapp/jsx/components/Consultation/Home.js
On the national tool the only condition for children is to display MAU for vitals, I think we can discuss this with the BA COP just to be sure if that implementation is required.

2023-11-12 14:27 UTC, Mathew77 commented on src/main/webapp/jsx/components/Otz/ServiceForm.js
No, that would be removed. Thanks

2023-11-13 14:03 UTC, dikumheartland commented on src/main/java/org/lamisplus/modules/hiv/repositories/HivEnrollmentRepository.java
The search query had `other_name ilike ''`. This made the result include lots of irrelevant records because a lot of clients have empty other_name. The fix was to make it like the other search params.

2023-11-15 13:49 UTC, Mathew77 commented
waiting for your approval @lilkersy, are they any pending issues that have not been addressed?

2023-12-15 10:11 UTC, closed without merging